version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'zookeeper'
    networks:
      - app-tier
    ports:
      - "2181:2181"
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#  myapp:
#    image: 'hello-world-kafka'
#    networks:
#      - kafka-net